services:
  - type: web
    name: healthcare-notes-app
    env: node
    plan: free
    runtime: node
    nodeVersion: 20
    buildCommand: npm install && npm run build && npm run migrate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /api/health
